n = int(input('Digite um número: '))
d = (n * 2)
t = (n * 3)
r2 = (n ** (1 / 2))
print('O Dobro de {} é: {}'.format(n, d))
print('O Triplo de {} é: {}'.format(n, t))
print('A Raiz quadrada de {} é: {:.0f}'.format(n, r2))
